UnsubscribeAll Event
pubnub/c-sharp pull request #175
Opened 2023-07-04 14:43 UTC by budgetpreneur

2023-07-14 07:07 UTC, mohitpubnub commented
Is it necessary to have channels and channelGroups value with UnsubscribeAll Event?
Isn't it the event type itself suggesting to remove all channels and groups from subscription.

2023-07-14 07:26 UTC, MikeDobrzan requested changes
UnsubscribeAll event and Unsubscribed state does not need any information about channels and channel groups

2023-07-14 08:07 UTC, budgetpreneur commented on src/Api/PubnubApi/EventEngine/Subscribe/States/UnsubscribedState.cs
> +        public IEnumerable<string> ChannelGroups;
I added `LeaveEffectHandler` where `LeaveInvocation` needs channels and channel groups to make REST API leave call through SubscribeManager2.
If we are doing different way, we can discuss on it.

2023-07-14 09:08 UTC, budgetpreneur commented on src/Api/PubnubApi/EventEngine/Subscribe/States/UnsubscribedState.cs
> +        public IEnumerable<string> ChannelGroups;
Rolled back Leave stuff.
Removed channels and channel groups from UnsubscribeAll.

2023-07-14 09:08 UTC, budgetpreneur commented on src/Api/PubnubApi/EventEngine/Subscribe/Events/SubscriptionEvents.cs
> +    }
ok..removed them.

2023-07-14 09:08 UTC, budgetpreneur commented
> channels and groups

removed  channels and groups

2023-07-17 05:44 UTC, mohitpubnub approved these changes

2023-07-17 05:49 UTC, merged